# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 10.10.0
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 20
      - run: pnpm i
      - run: pnpm build

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 10.10.0
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: pnpm i
      - run: pnpm publish --no-git-checks
        env:
          NPM_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}
  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 10.10.0
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      - run: pnpm i
      - run: pnpm publish --no-git-checks
        env:
          NPM_TOKEN: ${{secrets.GIT_HUB_TOKEN}}
